version: '3'

services:
  wpcas-survey-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3300:3000
    networks:
      - samagra_compass

networks:
  samagra_compass:
    external: true