version: '3'

services:
  wpcas-survey-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WPCAS_SERVICE_BACKEND_IP=http://localhost:4010
