export const surveys = [
  {
    id: '1',
    name: 'Suhama Hirani',
    role: 'Director of Medical Board',
    providedFeedback: true,
    getFeedback: false,
    questions: [
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
    ],
  },
  {
    id: '2',
    name: 'Ronald Richards',
    role: 'Chief Executive Officer',
    providedFeedback: true,
    getFeedback: true,
    questions: [
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
      'Do you think Sushama hirani achieved this level?',
    ],
  },
  {
    id: '3',
    name: 'Jenny Wilson',
    role: 'Finance',
    providedFeedback: false,
    getFeedback: true,
    questions: [
      '1Do you think Sushama hirani achieved this level?',
      '2Do you think Sushama hirani achieved this level?',
      '3Do you think Sushama hirani achieved this level?',
      '4Do you think Sushama hirani achieved this level?',
      '5Do you think Sushama hirani achieved this level?',
      '6Do you think Sushama hirani achieved this level?',
      '7Do you think Sushama hirani achieved this level?',
      '8Do you think Sushama hirani achieved this level?',
      '9Do you think Sushama hirani achieved this level?',
      '10Do you think Sushama hirani achieved this level?',
      '11Do you think Sushama hirani achieved this level?',
      '12Do you think Sushama hirani achieved this level?',
      '13Do you think Sushama hirani achieved this level?',
      '14Do you think Sushama hirani achieved this level?',
    ],
  },
];
